import React, { useState, useEffect } from "react";
import {
  Bell,
  AlertTriangle,
  ShieldAlert,
  CheckCircle,
  Trash2,
  Filter,
  Plus,
  X,
  Clock,
  Sparkles
} from "lucide-react";

export default function AlertsCenter() {
  const [alerts, setAlerts] = useState([]);
  const [loading, setLoading] = useState(true);
  const [filterSeverity, setFilterSeverity] = useState("ALL");
  const [showAddModal, setShowAddModal] = useState(false);
  const [newAlert, setNewAlert] = useState({
    title: "Worker without Helmet Detected",
    message: "Worker observed in zone B without required hardhat.",
    severity: "CRITICAL",
    source_agent: "Safety Agent (YOLOv11)"
  });

  useEffect(() => {
    fetchAlerts();
  }, []);

  const fetchAlerts = async () => {
    try {
      setLoading(true);
      const res = await fetch("http://127.0.0.1:8000/api/alerts");
      if (res.ok) {
        const data = await res.json();
        setAlerts(data);
      }
    } catch (err) {
      console.error("Error loading alerts:", err);
    } finally {
      setLoading(false);
    }
  };

  const handleResolve = async (alertId) => {
    try {
      const res = await fetch(`http://127.0.0.1:8000/api/alerts/${alertId}/resolve`, {
        method: "PUT"
      });
      if (res.ok) {
        fetchAlerts();
      }
    } catch (err) {
      console.error("Failed to resolve alert:", err);
    }
  };

  const handleDelete = async (alertId) => {
    try {
      const res = await fetch(`http://127.0.0.1:8000/api/alerts/${alertId}`, {
        method: "DELETE"
      });
      if (res.ok) {
        fetchAlerts();
      }
    } catch (err) {
      console.error("Failed to delete alert:", err);
    }
  };

  const handleCreate = async (e) => {
    e.preventDefault();
    try {
      const res = await fetch("http://127.0.0.1:8000/api/alerts", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(newAlert)
      });
      if (res.ok) {
        setShowAddModal(false);
        fetchAlerts();
      }
    } catch (err) {
      console.error("Failed to create alert:", err);
    }
  };

  const filtered = alerts.filter((a) => {
    if (filterSeverity === "ALL") return true;
    return a.severity?.toUpperCase() === filterSeverity.toUpperCase();
  });

  return (
    <div>
      {/* Title */}
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "24px", flexWrap: "wrap", gap: "16px" }}>
        <div>
          <h2 style={{ fontSize: "1.4rem", fontWeight: "700", color: "#fff", margin: "0 0 4px 0" }}>
            Alerts & Risk Notification Center
          </h2>
          <p style={{ color: "var(--text-muted)", fontSize: "0.85rem" }}>
            Autonomous alerts generated by YOLOv11 Safety, Weather forecasts, Budget monitors, and Schedule tracking
          </p>
        </div>

        <button
          className="btn-primary-ci"
          onClick={() => {
            setNewAlert({
              title: "Worker without Helmet Detected",
              message: "Worker observed in zone B without required hardhat.",
              severity: "CRITICAL",
              source_agent: "Safety Agent (YOLOv11)"
            });
            setShowAddModal(true);
          }}
        >
          <Plus size={18} /> Dispatch Site Alert
        </button>
      </div>

      {/* Filter Tabs */}
      <div style={{ display: "flex", gap: "10px", marginBottom: "20px", flexWrap: "wrap" }}>
        {["ALL", "CRITICAL", "HIGH", "MEDIUM"].map((sev) => (
          <button
            key={sev}
            className={`btn-secondary-ci ${filterSeverity === sev ? "active" : ""}`}
            style={{
              padding: "6px 14px",
              fontSize: "0.82rem",
              background: filterSeverity === sev ? "var(--primary)" : "#1e293b",
              color: "#fff",
              border: "none"
            }}
            onClick={() => setFilterSeverity(sev)}
          >
            {sev === "ALL" ? `All Alerts (${alerts.length})` : `${sev} (${alerts.filter(a => a.severity?.toUpperCase() === sev).length})`}
          </button>
        ))}
      </div>

      {/* Alerts Feed */}
      <div style={{ display: "flex", flexDirection: "column", gap: "14px" }}>
        {filtered.map((alert) => {
          const aId = alert._id || alert.id;
          const isResolved = alert.is_resolved;
          const sevColor =
            alert.severity === "CRITICAL"
              ? "#ef4444"
              : alert.severity === "HIGH"
              ? "#f59e0b"
              : "#3b82f6";

          return (
            <div
              key={aId}
              style={{
                background: "var(--bg-card)",
                border: "1px solid var(--border-color)",
                borderLeft: `5px solid ${sevColor}`,
                borderRadius: "12px",
                padding: "18px 22px",
                display: "flex",
                justifyContent: "space-between",
                alignItems: "flex-start",
                gap: "16px",
                opacity: isResolved ? 0.65 : 1
              }}
            >
              <div style={{ flexGrow: 1 }}>
                <div style={{ display: "flex", alignItems: "center", gap: "10px", marginBottom: "6px", flexWrap: "wrap" }}>
                  <span className={`badge-pill ${
                    alert.severity === "CRITICAL" ? "badge-danger" : alert.severity === "HIGH" ? "badge-warning" : "badge-info"
                  }`}>
                    {alert.severity}
                  </span>
                  <span style={{ fontSize: "0.8rem", color: "var(--text-muted)" }}>
                    Source: <strong style={{ color: "#e2e8f0" }}>{alert.source_agent || "Autonomous Agent"}</strong>
                  </span>
                  {isResolved && (
                    <span className="badge-pill badge-success">
                      <CheckCircle size={12} /> Resolved
                    </span>
                  )}
                </div>

                <h4 style={{ color: "#fff", fontSize: "1.05rem", fontWeight: "600", marginBottom: "4px" }}>
                  {alert.title}
                </h4>
                <p style={{ color: "var(--text-secondary)", fontSize: "0.88rem", lineHeight: "1.4", margin: 0 }}>
                  {alert.message}
                </p>

                {alert.created_at && (
                  <span style={{ display: "inline-flex", alignItems: "center", gap: "4px", fontSize: "0.75rem", color: "var(--text-muted)", marginTop: "8px" }}>
                    <Clock size={12} /> {alert.created_at}
                  </span>
                )}
              </div>

              <div style={{ display: "flex", gap: "8px", flexShrink: 0 }}>
                {!isResolved && (
                  <button
                    className="btn-secondary-ci"
                    style={{ padding: "6px 12px", fontSize: "0.8rem", color: "#34d399" }}
                    onClick={() => handleResolve(aId)}
                  >
                    <CheckCircle size={14} /> Resolve
                  </button>
                )}
                <button
                  className="btn-secondary-ci"
                  style={{ padding: "6px 10px", fontSize: "0.8rem", color: "#f87171" }}
                  onClick={() => handleDelete(aId)}
                >
                  <Trash2 size={14} />
                </button>
              </div>
            </div>
          );
        })}
      </div>

      {/* DISPATCH ALERT MODAL */}
      {showAddModal && (
        <div className="modal-backdrop-ci">
          <div className="modal-content-ci">
            <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "20px" }}>
              <h3 style={{ margin: 0, color: "#fff", fontSize: "1.2rem" }}>
                Dispatch Immediate Site Alert
              </h3>
              <button
                style={{ background: "transparent", border: "none", color: "#94a3b8", cursor: "pointer" }}
                onClick={() => setShowAddModal(false)}
              >
                <X size={20} />
              </button>
            </div>

            <form onSubmit={handleCreate}>
              <div style={{ display: "flex", flexDirection: "column", gap: "16px" }}>
                <div>
                  <label className="form-label-ci">Alert Title</label>
                  <input
                    type="text"
                    className="form-control-ci"
                    value={newAlert.title}
                    onChange={(e) => setNewAlert({ ...newAlert, title: e.target.value })}
                    required
                  />
                </div>

                <div>
                  <label className="form-label-ci">Severity Level</label>
                  <select
                    className="form-control-ci"
                    value={newAlert.severity}
                    onChange={(e) => setNewAlert({ ...newAlert, severity: e.target.value })}
                  >
                    <option value="CRITICAL">CRITICAL (Immediate Action Required)</option>
                    <option value="HIGH">HIGH (Urgent Attention)</option>
                    <option value="MEDIUM">MEDIUM (Standard Notice)</option>
                    <option value="LOW">LOW (Informational)</option>
                  </select>
                </div>

                <div>
                  <label className="form-label-ci">Source Agent / Department</label>
                  <input
                    type="text"
                    className="form-control-ci"
                    value={newAlert.source_agent}
                    onChange={(e) => setNewAlert({ ...newAlert, source_agent: e.target.value })}
                  />
                </div>

                <div>
                  <label className="form-label-ci">Incident Description & Instructions</label>
                  <textarea
                    rows={3}
                    className="form-control-ci"
                    value={newAlert.message}
                    onChange={(e) => setNewAlert({ ...newAlert, message: e.target.value })}
                    required
                  />
                </div>
              </div>

              <div style={{ marginTop: "24px", display: "flex", justifyContent: "flex-end", gap: "12px" }}>
                <button
                  type="button"
                  className="btn-secondary-ci"
                  onClick={() => setShowAddModal(false)}
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  className="btn-primary-ci"
                >
                  Broadcast Alert
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
}
